### ISSUE TITLE
Il faudrait mettre à jour les images de partages sociaux

### ISSUE THREAD

**Issue by borisschapira** [sudweb/2019#16]
### Comportement constaté

Les images de partage sociaux de Sud Web 2019 sont celles de Sud Web 2018.
https://github.com/sudweb/2019/tree/master/assets/images/social

### Comportement attendu

Les images 2019 :)

### Étapes pour reproduire le problème

- Utiliser https://cards-dev.twitter.com/validator et tester l'URL du site de Sud Web 2019

@sudweb/thym

**Comment by bertrandkeller** [comment]
Tout à fait, c'est à faire.

Merci

**Comment by bertrandkeller** [comment]
https://github.com/sudweb/2019/pull/17

**Comment by borisschapira** [comment]
_My bad_, j'avais oublié de préciser qu'après il faut aller sur les réseaux sociaux et vider le cache en ajoutant une _querystring_. J'ai vu que ça foirait sur Twitter, donc je l'ai fait en testant https://sudweb.fr/2019/?trdt dans les outils de développeurs. Je vous laisse voir pour les autres RS.

Avant:

![image](https://user-images.githubusercontent.com/284742/51194384-3e1d4e80-18eb-11e9-8f3d-97971ae1d920.png)

Après:

![capture d ecran 2019-01-15 a 17 29 56](https://user-images.githubusercontent.com/284742/51194400-45dcf300-18eb-11e9-83ad-96b4db3862ad.png)
